name: Render PDF
on: push
jobs:
    render-pdf:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: typst-community/setup-typst@v3
            - run: typst compile paper.typ paper.pdf
            - uses: actions/upload-artifact@v4
              with:
                  name: tlb
                  path: tlb.pdf