name: Render PDF
on: push
jobs:
    render-pdf:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: typst-community/setup-typst@v3
            - run: typst compile tlb.typ tlb.pdf
            - run: |
                git checkout --orphan ${{ github.ref }}-pdf
                git rm -rf .
                git add -f tlb.pdf
                git -c user.name="Will M. Farr" -c user.email="wfarr@flatironinstitute.org" commit -m "Building paper"
                git push -q -f origin ${{ github.ref }}-pdf